### PR TITLE
change base to focal

### PR DESCRIPTION
**Pull request by wferi**

### CODE REVIEW

**Review by cemiarni — CHANGES_REQUESTED** [review]
We do not supporting specific versions of linux distributions, we support all distros implicitly. We only require the minimum version of python. So the commit message should not mention the Ubuntu and its release names.

**Review by cemiarni — CHANGES_REQUESTED** [review]
I think it is not a good idea to remove the install of specific version of python. We should leave those lines unchanged except the python version numbers.
This commit should be fixed up to first commit of this pull request.

**Review by cemiarni — CHANGES_REQUESTED** [review]
We should not mention Ubuntu bionic here.

**Review by cemiarni — DISMISSED** [review]

**Comment by wferi** [comment]
Superseded by #32.

**Pull request closed without merging**
